# Generated by Django 5.0.6 on 2024-07-19 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='item_image',
            field=models.CharField(default='https://th.bing.com/th?id=OIP.fCc7R9uBPn0l4vJUjQihFAHaH_&w=240&h=259&c=8&rs=1&qlt=90&o=6&dpr=1.3&pid=3.1&rm=2', max_length=5000),
        ),
    ]
